# Author: Zhack Ariya
# HTTP Test Endpoints

### GET ALL ITEMS
GET http://localhost:5000/items HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6InpoYWNrIiwiZW1haWwiOiJtZUB6aGFja3kuY29tIn0sImV4cGlyZXNJbiI6ODY0MDAsImlhdCI6MTY3ODE5MzI3Nn0.28iLIVyvCOhq5_gtYiBPaOWnzeR6CINMDwcSEY3bKfw

### GET SINGLE ITEM
GET http://localhost:5000/items/1 HTTP/1.1

### ADD ITEM
POST http://localhost:5000/items HTTP/1.1
Content-Type: application/json

{
    "name": "New Item 3"
}

### DELETE ITEM
DELETE http://localhost:5000/items/7eccb3a3-fcf4-4da4-b12a-447d7087a14c HTTP/1.1

### UPDATE ITEM
PUT http://localhost:5000/items/7eccb3a3-fcf4-4da4-b12a-447d7087a14c HTTP/1.1
Content-Type: application/json

{
    "name": "Updated Item"
}


### Authentication calls

### GET TOKEN
POST http://localhost:5000/login HTTP/1.1
Content-Type: application/json

{
		 	"username": "zhack",
		 	"email": "me@zhacky.com"
   
}